name: Bug report
description: Report a problem with the scanner
labels: [bug]
body:
  - type: input
    id: url
    attributes:
      label: Scanned URL
      description: The URL that caused the problem (optional if sensitive)
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: What happened vs what was expected
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Command used
      render: bash
      placeholder: node dist/cli.js scan https://...
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Output / error
      render: text
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Node.js version
      placeholder: "e.g. 22.0.0"
    validations:
      required: true
