name: Feature request
description: Suggest an improvement or a new RGPD rule
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or uncovered case
      description: What situation does the scanner not currently handle?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: input
    id: reference
    attributes:
      label: Legal reference (if applicable)
      placeholder: "e.g. CNIL 2022, RGPD Art. 7, CEPD 03/2022"
    validations:
      required: false
